### ISSUE TITLE
Linux deamon compilation failed

### ISSUE THREAD

**Issue by anemol** [bitconnectcoin/bitconnectcoin#1]
make -f makefile.unix USE_UPNP=-
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/media/SSD/Workspace/bitconnectcoin/src -I/media/SSD/Workspace/bitconnectcoin/src/obj -I/media/SSD/Workspace/bitconnectcoin/src/leveldb/include -I/media/SSD/Workspace/bitconnectcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
alert.cpp:273:1: fatal error: opening dependency file obj/alert.d: Aucun fichier ou dossier de ce type
 }
 ^
compilation terminated.
make: *** [obj/alert.o] Erreur 1

**Comment by anemol** [comment]
obj directory missing.

**Comment by bitconnectcoin** [comment]
You need to create obj/zerocoin directory in /src (/src/obj/zerocoin) and recompile.

Also
We will update source code with the new design of window and linux wallet.
