### ISSUE TITLE
Staking and Coin Age

### ISSUE THREAD

**Issue by d3orn** [bitconnectcoin/bitconnectcoin#14]
There is some information missing.
Do I need a whole BCC Coin for staking? If yes what if I sent multiple transaction and with the last one I have 1 whole coin when is it old enough?

Could you add coin age to the GUI? it would help a lot

**Comment by owner232** [comment]
Minimum Stake Age : 15 Days; Maximum Stake Age : 90 Days

**Comment by bitconnectcoin** [comment]
Read following guide: https://bitconnect.co/bitconnect-learning/69/what-if-my-staking-coins-are-in-multiple-addresses-in-the-same-wallet
https://bitconnect.co/bitconnect-learning/67/am-i-required-to-keep-my-desktop-wallet-connected-247
