### ISSUE TITLE
Linux daemon compilation failed (zerocoin)

### ISSUE THREAD

**Issue by anemol** [bitconnectcoin/bitconnectcoin#2]
make -f makefile.unix USE_UPNP=-
/bin/sh ../share/genbuild.sh obj/build.h
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/media/SSD/Workspace/bitconnectcoin/src -I/media/SSD/Workspace/bitconnectcoin/src/obj -I/media/SSD/Workspace/bitconnectcoin/src/leveldb/include -I/media/SSD/Workspace/bitconnectcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/zerocoin/Accumulator.d -o obj/zerocoin/Accumulator.o zerocoin/Accumulator.cpp
zerocoin/Accumulator.cpp:106:1: fatal error: opening dependency file obj/zerocoin/Accumulator.d: Aucun fichier ou dossier de ce type
 } /* namespace libzerocoin */
 ^
compilation terminated.
make: *** [obj/zerocoin/Accumulator.o] Erreur 1

**Comment by scorpio18** [comment]
just go to the obj folder and create directory zerocoin and then try again to compile

**Comment by bitconnectcoin** [comment]
You need to create obj/zerocoin directory in /src (/src/obj/zerocoin) and recompile.

Also
We will update source code with the new design of window and linux wallet.
