### ISSUE TITLE
Account issues

### ISSUE THREAD

**Issue by Joonbr** [bitconnectcoin/bitconnectcoin#45]
I requested from the 08/11/2017 disabled the Google Authenticator, since I deleted the data of the mobile.
More than 40 e-mails were sent but until today (10/01/2018) the company did not state.
How can a company currently worth 2,113,817,188.00 Market Cap, not have the least respect with the user / investor.
Applications have been sent including facebook, unsuccessfully and I was blocked by the moderator.
I am extremely outraged and puzzled by the situation !!!!

**Comment by cryptopramod2018** [comment]
@bitconnectcoin : Now that you're officially DEAD, please let me know what my 7 BCC is worth. Not even able to exchange it for bitcoin. So you stole all the money and ran away. Right?

I should have known better than to trust your no-good ponzi ass.

**Comment by Joonbr** [comment]
Scam ponzi fucking mothers!!!!

**Comment by cryptopramod2018** [comment]
SHITCOIN!!! @bitconnectcoin @bitconnectcoin

**Comment by Joonbr** [comment]
goodbye big and  never more bitconnect # **_bitconnectX_**(another ponzi and scam, pay attention very dangerous people!!!!)
