### ISSUE TITLE
QT Wallet won't sync (I've tried everything....)

### ISSUE THREAD

**Issue by jameswyns** [bitconnectcoin/bitconnectcoin#46]
My Bitconnect QT is out of sync,,,, running on 2-3 connections... 

I've done everything on the bitconnect page on why the wallets wont sync.... but still doesn't work?

**Comment by jameswyns** [comment]
Is there any special IP or port setting to use? Do I connect through SOCKS proxy? It checked currently... IP 127.0.0.1 PORT 9239... SOCKS VER 4.

My debug log also has a lot of connection time outs...

**Comment by BCUser12** [comment]
Do not use SOCKS.  Leave it unchecked.
All solutions have been posted on this forum.  Read everything in the forum carefully.  EVERYTHING!
Read all of my posts.

HOWTO: Solve the QT Wallet Not Syncing Issue #41
https://github.com/bitconnectcoin/bitconnectcoin/issues/41

Bitconnect-Qt wallet won't sync on Mac OSX 
https://github.com/bitconnectcoin/bitconnectcoin/issues/22

BITCONNECT QT WALLET OUT OF SYNC
https://github.com/bitconnectcoin/bitconnectcoin/issues/19

0 Active Connections
https://github.com/bitconnectcoin/bitconnectcoin/issues/13

**Comment by aaronykc** [comment]
hi BCUser12 ive read everything u listed but i cant find the bitconnect folder anywhere on my mac.
user/library/application support the file isnt there.

**Comment by BCUser12** [comment]
Usually these are system files and may be hidden.  I use a PC,  On the PC you have to reveal hidden files.  Read other Mac threads for assistance.

**Comment by jameswyns** [comment]
Perfect, I got it working man! Thanks for your help!
    On Friday, January 19, 2018, 12:43:36 PM EST, BCUser12 <notifications@github.com> wrote:  
 
 
Usually these are system files and may be hidden. I use a PC, On the PC you have to reveal hidden files. Read other Mac threads for assistance.

**Comment by BCUser12** [comment]
Wonderful, if you see other people struggling, please help them and use my references.  I'm a bit overwhelmed here.  Thanks.
