### ISSUE TITLE
pending transactions

### ISSUE THREAD

**Issue by chetubc** [bitconnectcoin/bitconnectcoin#66]
Hi,
my transaction is pending without a transaction id, what I should do.
Please help.

thanks,
Chetan

**Comment by mattviki** [comment]
The exchange does not work. People exchange #BCC coins with #BTC on your exchange and when they withdraw BTC to their external wallets, but you DON'T process the transactions and don't send the BTC to the blockchain. Will you do something about it?

**Comment by vogue20033** [comment]
Contact the BCC support

**Comment by chetubc** [comment]
Hi,
Their support don't work. 
It doesn't sound appropriate, but I did follow one of the post from bitconnect FB community, and it asked me to utilize the clickhere link, if we have any pending transactions, i did without any trxid,(with some txt indicated on that fb post) and boom, transactions happened and confirmed :).

chetubc
