### ISSUE TITLE
Pending BTC withdraw transactions without TXid

### ISSUE THREAD

**Issue by mattviki** [bitconnectcoin/bitconnectcoin#67]
The exchange does not work. People exchange #BCC coins with #BTC on your exchange and when they withdraw BTC to their external wallets, but you DON'T process the transactions and don't send the BTC to the blockchain. Will you do something about it?

**Comment by kanok1991** [comment]
what?

**Comment by mattviki** [comment]
Something to help the poor bastards that got caught in this second trap?

**Comment by kanok1991** [comment]
how should i do?

**Comment by mattviki** [comment]
All transaction I monitored were processed and arrived to external wallets.
